struct employee{
	char name[30];
	int dob;
	int id;
	char sex;
	int age;
	char dept;
	float salary;
	char email[35];
	long int phone;
	struct employee * link;
};
struct employee * insertemployee(struct employee * head,struct employee *ptr);
void print(struct employee *head);
void retrievename(struct employee * head,char dname[30]);
void retrieveid(struct employee * head,int did);
void retrieveage(struct employee * head,int dage);
void retrievedob(struct employee * head,int ddob);
void retrievesex(struct employee * head,char dsex);
void retrievedept(struct employee * head,char ddept[30]);
void retrieveemail(struct employee * head,char demail[30]);
void retrievesalary(struct employee* head,float dsalary);
void retrievephone(struct employee* head,long int dphone);
struct employee * deletebyname(struct employee * head, char dname[30]);
struct employee * read();
struct employee * updatename(struct employee * head,int did, char dnameaf[30]);
struct employee * updateemail(struct employee * head,int did, char demailaf[30]);
struct employee * updatedept(struct employee * head,int did, char ddeptaf[30]);
struct employee * updatesex(struct employee * head,int did, char dsex);
struct employee * updateid(struct employee * head,int did, int didaf);
struct employee * updatedob(struct employee * head,int did, int dobaf);
struct employee * updateage(struct employee * head,int did, int dageaf);
struct employee * updatesalary(struct employee* head,int did, float dsalaf);
struct employee * updatephone(struct employee * head,int did, long int dphone);
